#!/bin/sh -e
#
# Build rpm package for rshim driver for x86_64 and aarch64.
# The script generates source rpm, then builds x86_64 or aarch64 rpm depending
# on the CPU platform it's running on.
#
# Usage:
#   ./build-rpm
#

topdir=$(pwd)/rpmbuild
[ -d $topdir ] && rm -rf $topdir
mkdir -p $topdir/{BUILD,BUILDROOT,RPMS,SOURCES,SPECS,SRPMS}

# Generate rshim.spec
./bootstrap.sh
./configure
make
cp rshim.spec $topdir/SPECS/

# Generate source tarball
rm -f *.tar.gz
make dist  &> /dev/null   # xxx.tar.gz is not valid. just use its name
tgz=$(ls *.tar.gz)
version=$(basename $tgz .tar.gz | sed 's/rshim-//')
git archive -o $tgz --prefix=${version}/ HEAD
mv $tgz $topdir/SOURCES/

#
# Generate source RPM
#
rpmbuild --define "_topdir ${topdir}" -bs $topdir/SPECS/rshim.spec
src_rpm=$(echo $topdir/SRPMS/rshim-*.src.rpm)
if [ ! -e "${src_rpm}" ]; then
  echo "${src_rpm} not found"
  exit
fi

#
# Build rshim RPM
#
rpmbuild --define "_topdir ${topdir}" --rebuild ${src_rpm}
x64_rpm=$(echo ${topdir}/RPMS/x86_64/${name}*.rpm)
arm_rpm=$(echo ${topdir}/RPMS/aarch64/${name}*.rpm)
if [ -f "${x64_rpm}" ]; then
  echo "x86_64 RPM: ${x64_rpm}"
fi
if [ -f "${arm_rpm}" ]; then
  echo "aarch64 RPM: ${arm_rpm}"
fi
